### PR TITLE
Deleting setup.py and tox.ini and adding pyproject.lock

### PR DESCRIPTION
**Pull request by tmsv**
+ little changes to pyproject.toml

### CODE REVIEW

**Comment by sobolevn** [comment]
@tmsv please check, why `travis` is failing.

**Comment by tmsv** [comment]
> can you please remove pycodestyle direct dev dependency?

@sobolevn Done. I commited directly to the branch because of littleness and simplicty of the edit. I hope it's ok.

**Comment by sobolevn** [comment]
@tmsv travis is still failing

**Comment by tmsv** [comment]
> @tmsv travis is still failing

@sobolevn I tried to find solution but didn't find anything smarter then to copy [this file](https://github.com/sobolevn/jinja2-git/blob/master/.travis.yml).

If it's not OK, can you provide some guidance please? Now I act blindly.

**Comment by sobolevn** [comment]
There's a problem with `poetry.lock`:

> Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
                                                                                                              
> [SolverProblemError]                                                                           
> Because dump-env depends on pytest-flake8 (^1.0) which doesn't match any versions, version solving failed.

**Comment by sobolevn** [comment]
The easy way is to:
1. remove your `virtualenv`
2. remove `pyproject.lock`
3. make sure that `pyproject.toml` is correct
4. reinstall everything
5. create lock file with `pyproject.lock` (or it can be created automatically)

**Comment by sobolevn** [comment]
@tmsv now we are missing `delegator` module. Can you please add it to `dev-dependencies`? It should be the last change.

**Comment by tmsv** [comment]
@sobolevn hi there! I updated `pyproject.toml` and `pyproject.lock` by `poetry add --dev delegator`. Sorry for delay with this small edit.

If everything is OK, can you please tell me about next steps?
Thank you!

**Comment by sobolevn** [comment]
There is a merge conflict in `pyproject.toml`. Can you please fix them?

**Comment by tmsv** [comment]
@sobolevn I commited changes. Is everything ok now? What we are going to do next?

**Comment by tmsv** [comment]
> You can see the build result in the bottom bar of this PR. Here's the link: https://travis-ci.org/sobolevn/dump-env/builds/440939105?utm_source=github_status&utm_medium=notification
> 
> It is still failing.

So how can I fix it? I'm confused

**Comment by sobolevn** [comment]
Here's the warning message: https://travis-ci.org/sobolevn/dump-env/jobs/440939107#L583

It seems that `delegator` module has changed its API.
You need to refactor it to work again.

**Comment by tmsv** [comment]
> Here's the warning message: https://travis-ci.org/sobolevn/dump-env/jobs/440939107#L583
> 
> It seems that `delegator` module has changed its API.
> You need to refactor it to work again.

So I need to delete it from `pyproject.toml` and `pyproject.lock` and add it again, right? Or I need to refactor both files from the beginning?

**Comment by sobolevn** [comment]
You need to refactor test cases.

**Comment by tmsv** [comment]
> You need to refactor test cases.

What does it mean "rafactor" and "test cases" in this context?

**Comment by sobolevn** [comment]
Sorry, I have missed one important thing: you are installing wrong `delegator` package. 
That's why these tests are failing.

You need to install this package instead: https://pypi.org/project/delegator.py/

**Comment by tmsv** [comment]
> Sorry, I have missed one important thing: you are installing wrong `delegator` package.
> That's why these tests are failing.
> 
> You need to install this package instead: https://pypi.org/project/delegator.py/

Can you please check if everything is ok?

**Comment by sobolevn** [comment]
@tmsv you can look at the travis build for the required information. As you can see the build is still failing. I guess it happens because of the new `delegator` release: `0.1.1`. Try to use the previous version.

**Comment by tmsv** [comment]
> @tmsv you can look at the travis build for the required information. As you can see the build is still failing. I guess it happens because of the new `delegator` release: `0.1.1`. Try to use the previous version.

I tried both previous version (0.1.0) and the one before it (0.0.14) and nevertheless it cruches again. I want to understand what's the reason of Error. But I couldn't google anything relevant except general info.

Can you help with the direction?

**Comment by tmsv** [comment]
@sobolevn  I tried 4 last versions of `delegator.py` (`0.0.13`; `0.0.14`; `0.1.0` and `0.1.1`) and none of them works. Futhermore I noticed that they give the same Error in travis. So I doubt that the Error is caused by `delegator.py` version.
Do you have any thoughts how to solve problem?

**Pull request closed without merging**
